version: "3.8"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '13306:3306'
    volumes:
      - .local/mysql-data:/var/lib/mysql
      - .local/mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: fmbm_feathers_sandbox

  mongo:
    image: mongo
    restart: always
    ports:
      - 17017:27017
    volumes:
      - .local/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: fmbm_feathers_sandbox
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  solr:
    image: solr:8
    ports:
      - '18983:8983'
    volumes:
      - .local/solr-data/:/var/solr/data/
      - .local/solr-init.sh:/docker-entrypoint-initdb.d/solr-init.sh:ro
      - .local/solr-init/books:/tmp/solr-init/books

  node:
    image: 'node:14'
    restart: always
    ports:
      - '13030:3030'
    depends_on:
      - mysql
      - mongo
      - solr
    working_dir: /home/node/app
    environment:
      - PORT=3030
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: [
      "./wait-for-it.sh", 
      "mysql:3306", 
      "mongo:27017", 
      "solr:8983", 
      "-s",
      "-t",
      "0", 
      "--",
      "./start.sh"
    ]